---
- name: Installation du Network Seurity Group VM Linux
  azure_rm_securitygroup:
    name: "{{ nsg_linux_name }}"
    resource_group: "{{ rg_name }}"
    purge_rules: yes
    rules:
        - name: AllowSsh
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 100
          direction: Inbound
...