---
- name: Installation du Network Seurity Group VM Windows
  azure_rm_securitygroup:
    name: "{{ nsg_win_name }}"
    resource_group: "{{ rg_name }}"
    purge_rules: yes
    rules:
        - name: AllowRDP
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 100
          direction: Inbound
...